dubture_f_fmpeg:
    ffmpeg_binary: /opt/VankosoftProjects/VideoPlatform/unsecured/ffmpeg
    ffprobe_binary: /opt/VankosoftProjects/VideoPlatform/unsecured/ffprobe
    binary_timeout: 300 # Use 0 for infinite
    threads_count: 4
    temporary_directory: /var/ffmpeg-tmp