knp_gaufrette:
    adapters:
        vs_application_profile:
            local:
                directory: "%vs_cms.filemanager_shared_media_gaufrette.profile%"
                create: true
        vs_application_filemanager:
            local:
                directory: "%vs_cms.filemanager_shared_media_gaufrette.filemanager%"
                create: true
        vs_application_app_pictures:
            local:
                directory: "%vs_application.filemanager_shared_media_gaufrette.app_pictures%"
        vs_application_slider:
            local:
                directory: "%vs_cms.filemanager_shared_media_gaufrette.slider%"
                create: true
        vs_vvp_videos:
            local:
                directory: "%vs_vvp.videos_directory%"
                create: true
        vs_vvp_coconut_output:
            local:
                directory: "%vs_vvp.coconut_output_directory%"
                create: true
        vs_vvp_actor_photos:
            local:
                directory: "%vs_vvp.actor_photos_directory%"
                create: true
        vs_vvp_videos_user_signatured:
            local:
                directory: "%vs_vvp.videos_user_signatured_directory%"
        vs_vvp_videos_digitalocean:
            service:
                id: vs_vvp.digital_ocean_original_videos_adapter
        vs_vvp_videos_digitalocean_coconut_output:
            service:
                id: vs_vvp.digital_ocean_coconut_output_adapter

    filesystems:
        vs_application_profile:
            adapter: "%vs_cms.gaufrette.profile.filesystem%"
        vs_application_filemanager:
            adapter: "%vs_cms.gaufrette.filemanager.filesystem%"
        vs_application_app_pictures:
            adapter: "%vs_application.gaufrette.app_pictures.filesystem%"
        vs_application_slider:
            adapter: "%vs_cms.gaufrette.slider.filesystem%"
        vs_vvp_videos:
            adapter: "vs_vvp_videos"
        vs_vvp_coconut_output:
            adapter: "vs_vvp_coconut_output"
        vs_vvp_actor_photos:
            adapter: "vs_vvp_actor_photos"
        vs_vvp_videos_user_signatured:
            adapter: "vs_vvp_videos_user_signatured"
        vs_vvp_videos_digitalocean:
            adapter: "vs_vvp_videos_digitalocean"
        vs_vvp_videos_digitalocean_coconut_output:
            adapter: "vs_vvp_videos_digitalocean_coconut_output"
            
