knp_gaufrette:
    stream_wrapper: ~
    
    adapters:
        vs_vvp_videos:
            local:
                directory: "%vs_vvp.videos_directory%"
                create: true
        vs_vvp_video_clips:
            local:
                directory: "%vs_vvp.video_clips_directory%"
                create: true
        vs_vvp_coconut_output:
            local:
                directory: "%vs_vvp.coconut_output_directory%"
                create: true
        vs_vvp_actor_photos:
            local:
                directory: "%vs_vvp.actor_photos_directory%"
                create: true
        vs_vvp_videos_user_signatured:
            local:
                directory: "%vs_vvp.videos_user_signatured_directory%"
        vs_vvp_videos_digitalocean:
            service:
                id: vs_vvp.digital_ocean_original_videos_adapter
        vs_vvp_videos_digitalocean_coconut_output:
            service:
                id: vs_vvp.digital_ocean_coconut_output_adapter
        vs_vvp_youtube_photos:
            local:
                directory: "%vs_vvp.youtube_photos_directory%"
                create: true

    filesystems:
        vs_vvp_videos:
            adapter: "vs_vvp_videos"
        vs_vvp_video_clips:
            adapter: "vs_vvp_video_clips"
        vs_vvp_coconut_output:
            adapter: "vs_vvp_coconut_output"
        vs_vvp_actor_photos:
            adapter: "vs_vvp_actor_photos"
        vs_vvp_videos_user_signatured:
            adapter: "vs_vvp_videos_user_signatured"
        vs_vvp_videos_digitalocean:
            adapter: "vs_vvp_videos_digitalocean"
        vs_vvp_videos_digitalocean_coconut_output:
            adapter: "vs_vvp_videos_digitalocean_coconut_output"
        vs_vvp_youtube_photos:
            adapter: "vs_vvp_youtube_photos"
