oneup_flysystem:
    adapters:
        vs_application_app_pictures:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.app_pictures%"
        vs_application_profile:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.profile%"
        vs_application_filemanager:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.filemanager%"
        vs_application_slider:
            local:
                location: "%vs_cms.filemanager_shared_media_gaufrette.slider%"
        
        vs_vvp.videos_adapter:
            local:
                location: '%vs_vvp.videos_directory%'
        vs_vvp.coconut_output_adapter:
            local:
                location: '%vs_vvp.coconut_output_directory%'
        vs_vvp.videos_user_signatured_adapter:
            local:
                location: '%vs_vvp.videos_user_signatured_directory%'
                
    filesystems:
        vs_application_app_pictures:
            adapter: "%vs_cms.gaufrette.app_pictures.filesystem%"
        vs_application_profile:
            adapter: "%vs_cms.gaufrette.profile.filesystem%"
        vs_application_filemanager:
            adapter: "%vs_cms.gaufrette.filemanager.filesystem%"
        vs_application_slider:
            adapter: "%vs_cms.gaufrette.slider.filesystem%"
        
        vs_vvp.filesystems.local:
            adapter: vs_vvp.videos_adapter
            alias: League\Flysystem\Filesystem
        vs_vvp.filesystems.coconut_output:
            adapter: vs_vvp.coconut_output_adapter
        vs_vvp.filesystems.videos_user_signatured:
            adapter: vs_vvp.videos_user_signatured_adapter
