#####################################################################################################
# Chunks Config: https://github.com/1up-lab/OneupUploaderBundle/blob/main/doc/chunked_uploads.md
#####################################################################################################

############################################################################################
# Set The Storage You Want to Use
#-------------------------------------
# https://github.com/1up-lab/OneupUploaderBundle/blob/master/doc/gaufrette_storage.md
# https://github.com/1up-lab/OneupUploaderBundle/blob/main/doc/flysystem_storage.md
############################################################################################

oneup_uploader:
    chunks:
        maxage: 86400
        storage:
            directory: '%kernel.project_dir%/var/uploader_chunks'
#         storage:
#             type: flysystem
#             filesystem: oneup_flysystem.vs_vvp_videos_digitalocean_chunks_filesystem
#             stream_wrapper: 's3://videoplatform-uploader-chunks'
#             prefix: ''

    mappings:
        videos_local:
            frontend: blueimp
            
            storage:
                type: flysystem
                filesystem: oneup_flysystem.vs_vvp_videos_filesystem
        
        videos_digitalocean:
            frontend: blueimp
            
            storage:
                type: flysystem
                filesystem: oneup_flysystem.vs_vvp_videos_digitalocean_filesystem
                
        coconut_output:
            frontend: custom
            custom_frontend:
                class: App\Controller\Api\CoconutStorageController
                name: coconut_output
