# @see https://github.com/Sylius/SyliusResourceBundle/blob/master/docs/index.md
sylius_resource:
    #######################################################################################################################
    # Override default settings
    # -------------------------
    # You Can To Override Many Resource Parameters For All Resources (Including VankoSoft Bundles)
    # View Available Settings in 
    #     \Sylius\Bundle\ResourceBundle\DependencyInjection\Configuration::addSettingsSection(ArrayNodeDefinition $node)
    #######################################################################################################################
    settings:
        paginate: 10
        
    #######################################################################################################################
    # Configure your resources
    #######################################################################################################################
    resources:
        vs_vvp.video_category:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoCategory
                repository: App\Repository\MoviesRepository
                controller: App\Controller\AdminPanel\VideoCategoryController
                form:       App\Form\VideoCategoryForm
                
        vs_vvp.video:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Video
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\VideoController
                form:       App\Form\VideoForm
                
        vs_vvp.video_photo:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoPhoto
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                
        vs_vvp.video_file:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoFile
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                
        vs_vvp.coconut_job:
            driver: doctrine/orm
            classes:
                model:      App\Entity\CoconutJob
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                
        vs_vvp.actor:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Actor
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\ActorController
                form:       App\Form\ActorForm
                
        vs_vvp.actor_photo:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ActorPhoto
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        
        vs_vvp.video_platform_application:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoPlatformApplication
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\VideoPlatformApplicationController
                form:       App\Form\VideoPlatformApplicationForm
        
        vs_vvp.video_platform_settings:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoPlatformSettings
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\VideoPlatformSettingsController
                form:       App\Form\VideoPlatformSettingsForm
                
        vs_vvp.video_platform_storage:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoPlatformStorage
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\VideoPlatformStorageController
                form:       App\Form\VideoPlatformStorageForm
                
        vs_vvp.coconut_settings:
            driver: doctrine/orm
            classes:
                model:      App\Entity\CoconutSettings
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\CoconutSettingsController
                form:       App\Form\CoconutSettingsForm
                
        vs_vvp.google_cloud_project:
            driver: doctrine/orm
            classes:
                model:      App\Entity\GoogleCloudProject
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\GoogleCloudProjectController
                form:       App\Form\GoogleCloudProjectForm
                
        vs_vvp.youtube_channel:
            driver: doctrine/orm
            classes:
                model:      App\Entity\YoutubeChannel
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\YoutubeChannelController
                form:       App\Form\YoutubeChannelForm
                
        vs_vvp.youtube_channel_photo:
            driver: doctrine/orm
            classes:
                model:      App\Entity\YoutubeChannelPhoto
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                
        vs_vvp.video_review:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoReview
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                
        vs_vvp.video_comment:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoComment
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                
        vs_vvp.video_genre:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoGenre
                repository: App\Repository\GenresRepository
                controller: App\Controller\AdminPanel\VideoGenreController
                form:       App\Form\VideoGenreForm
                
        vs_vvp.actor_review:
            driver: doctrine/orm
            classes:
                model:      App\Entity\ActorReview
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                
#         vs_vvp.actor_comment:
#             driver: doctrine/orm
#             classes:
#                 model:      App\Entity\ActorComment
#                 repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository

        vs_vvp.video_clip:
            driver: doctrine/orm
            classes:
                model:      App\Entity\VideoClip
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
