services:
    _defaults:
        autowire: true
        autoconfigure: true

    app_video_provider_local_storage:
        class: App\Component\VideoProviders\LocalStorageVideoProvider
        arguments:
            - '@vs_vvp.repository.video'
            - '%vankosoft_host%'
            - '@liip_imagine.cache.manager'
            - '@app_video_transcoder_coconut'
            
    app_video_service_local_storage:
        class: App\Component\VideoPlayer\VideoService
        arguments:
            - '@app_video_provider_local_storage'


