version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: video_platform_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            # MYSQL_ROOT_PASSWORD: 'VanzVideoPlayer_123'
            MYSQL_DATABASE: 'VanzVideoPlayer'
        networks:
            - video_platform

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: video_platform_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - video_platform

    # Symfony apache project container
    www:
        image: iatanasov77/vs-application-server
        container_name: video_platform_application
        ports:
          - "8090:80"
        volumes:
            - ./infrastructure/docker.d/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - video_platform

networks:
    video_platform:

volumes:
    db-data: