app_youtube_player_search:
    path: /youtube/search
    controller: App\Controller\VanzVideoPlayer\YoutubePlayerController::search
    
app_youtube_player_mychannel:
    path: /youtube/mychannel
    controller: App\Controller\VanzVideoPlayer\YoutubePlayerController::mychannel

app_video_player_access_denied:
    path: /error/access-denied
    controller: App\Controller\Application\ErrorController::accessDenied
    
app_video_player_read:
    path: /videos/{id}/read
    controller: App\Controller\Application\VideosController::read
    options:
        expose: true
        
app_video_player_read_transcoded:
    path: /videos-transcoded/{id}-{format}/read
    controller: App\Controller\Application\VideosController::readTranscoded
    options:
        expose: true

app_video_player_index:
    path: /video-player/local-storage
    controller: App\Controller\VanzVideoPlayer\VideoPlayerController::index
