vs_api_platform:
    resource: "@VSApiBundle/Resources/config/routing/api_platform.yaml"
    prefix: /api

vs_api_users:
    resource: "@VSApiBundle/Resources/config/routing/api.yaml"
    prefix: /api

vs_api_test_index:
    path: /api/test-index
    controller: App\Controller\Api\TestController::index
    
vs_api_coconut_webhook_video_job:
    path: /api/coconut/video-job-webhook/{apiToken}
    controller: App\Controller\Api\CoconutWebhookController::videoJobNotification
    
vs_api_coconut_webhook_clip_job:
    path: /api/coconut/clip-job-webhook/{apiToken}
    controller: App\Controller\Api\CoconutWebhookController::clipJobNotification
    
vs_api_coconut_storage:
    path: /api/coconut/storage
    controller: App\Controller\Api\CoconutStorageController::index
