knp_gaufrette:
    adapters:
        vs_vvp_videos:
            local:
                directory: "%vs_vvp.videos_directory%"
                create: true
        vs_vvp_video_clips:
            local:
                directory: "%vs_vvp.video_clips_directory%"
                create: true
        vs_vvp_coconut_output:
            local:
                directory: "%vs_vvp.coconut_output_directory%"
                create: true
        vs_vvp_videos_user_signatured:
            local:
                directory: "%vs_vvp.videos_user_signatured_directory%"
                create: true
    filesystems:
        vs_vvp_videos:
            adapter: "vs_vvp_videos"
        vs_vvp_video_clips:
            adapter: "vs_vvp_video_clips"
        vs_vvp_coconut_output:
            adapter: "vs_vvp_coconut_output"
        vs_vvp_videos_user_signatured:
            adapter: "vs_vvp_videos_user_signatured"

