knp_gaufrette:
    adapters:
        vs_application_profile:
            local:
                directory: "%vs_cms.filemanager_shared_media_gaufrette.profile%"
                create: true
        vs_application_filemanager:
            local:
                directory: "%vs_cms.filemanager_shared_media_gaufrette.filemanager%"
                create: true
        vs_application_app_pictures:
            local:
                directory: "%vs_application.filemanager_shared_media_gaufrette.app_pictures%"
        vs_vvp_videos:
            local:
                directory: "%vs_vvp.videos_directory%"
                create: true
        vs_vvp_video_clips:
            local:
                directory: "%vs_vvp.video_clips_directory%"
                create: true
        vs_vvp_coconut_output:
            local:
                directory: "%vs_vvp.coconut_output_directory%"
                create: true
        vs_vvp_videos_user_signatured:
            local:
                directory: "%vs_vvp.videos_user_signatured_directory%"
                create: true
    filesystems:
        vs_application_profile:
            adapter: "%vs_cms.gaufrette.profile.filesystem%"
        vs_application_filemanager:
            adapter: "%vs_cms.gaufrette.filemanager.filesystem%"
        vs_application_app_pictures:
            adapter: "%vs_application.gaufrette.app_pictures.filesystem%"
        vs_vvp_videos:
            adapter: "vs_vvp_videos"
        vs_vvp_video_clips:
            adapter: "vs_vvp_video_clips"
        vs_vvp_coconut_output:
            adapter: "vs_vvp_coconut_output"
        vs_vvp_videos_user_signatured:
            adapter: "vs_vvp_videos_user_signatured"

