# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
    
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public/shared_media/gaufrette/profile"
                    - "%kernel.project_dir%/public/shared_media/gaufrette/filemanager"
                    - "%kernel.project_dir%/public/shared_media/artgris"
                    - "%kernel.project_dir%/public/shared_media/gaufrette/videos"
                    - "%kernel.project_dir%/public/shared_media/gaufrette/actors"
                    - "%kernel.project_dir%/public/shared_media/gaufrette/slider"
                    - "%kernel.project_dir%/public/shared_media/gaufrette/youtube_photos"

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public/video-platform"
                cache_prefix: "media/cache"

    filter_sets:
        cache: ~
        
        profile_form_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }
        
        users_crud_index_thumb:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
                background: { size: [50, 50], position: center, color: '#000000' }
                
        file_manager_files_thumb:
            quality: 75
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
                background: { size: [50, 50], position: center, color: '#000000' }
                
        slider_background_photo:
            quality: 75
            filters:
                thumbnail: { size: [1920, 1280], mode: outbound }
                background: { size: [1924, 1284], position: center, color: '#000000' }
                
        actor_listing_photo:
            quality: 75
            filters:
                thumbnail: { size: [240, 340], mode: outbound }
                background: { size: [244, 344], position: center, color: '#000000' }
                
        movies_listing_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [240, 340], mode: outbound }
                background: { size: [244, 344], position: center, color: '#000000' }
                
        video_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                background: { size: [124, 94], position: center, color: '#000000' }
        
        video_thumbnail_plyr:
            quality: 75
            filters:
                thumbnail: { size: [300, 200], mode: outbound }
                background: { size: [304, 204], position: center, color: '#000000' }
                
        video_photos_gallery_thumb:
            quality: 75
            filters:
                thumbnail: { size: [336, 224], mode: outbound }
                background: { size: [340, 228], position: center, color: '#000000' }
                
        video_photos_gallery_preview:
            quality: 75
            filters:
                thumbnail: { size: [1920, 1280], mode: outbound }
                background: { size: [1924, 1284], position: center, color: '#000000' }
                
        actor_photos_gallery_thumb:
            quality: 75
            filters:
                thumbnail: { size: [336, 224], mode: outbound }
                background: { size: [340, 228], position: center, color: '#000000' }
                
        actor_photos_gallery_preview:
            quality: 75
            filters:
                thumbnail: { size: [1920, 1280], mode: outbound }
                background: { size: [1924, 1284], position: center, color: '#000000' }
                
        photoswipe_gallery_preview:
            quality: 75
            filters:
                thumbnail: { size: [1920, 1280], mode: outbound }
                background: { size: [1924, 1284], position: center, color: '#000000' }
                
        video_watermark:
            quality: 75
            filters:
                thumbnail: { size: [400, 40], mode: outbound }
                background: { size: [404, 44], position: center, color: '#000000' }
