framework:
    assets:
        packages:
            default:
                json_manifest_path: '%kernel.project_dir%/public/video-platform/build/default/manifest.json'
            video-platform-theme:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/video-platform-theme/manifest.json'
webpack_encore:
    output_path: '%kernel.project_dir%/public/video-platform/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/video-platform/build/default'
        VideoPlatformTheme: '%kernel.project_dir%/public/shared_assets/build/video-platform-theme'
