imports:
    #- { resource: "@VSApiBundle/Resources/config/app/security.yaml" }
    - { resource: "@VSApiBundle/Resources/config/app/api_platform.yaml" }
    - { resource: "@VSApiBundle/Resources/config/app/serializer.yaml" }
    - { resource: "@VSApiBundle/Resources/config/app/lexik_jwt_authentication.yaml" }
    - { resource: "@VSApiBundle/Resources/config/app/nelmio_cors.yaml" }
    - { resource: "@VSApiBundle/Resources/config/app/mercure.yaml" }

vs_api:
    enabled: true
    
    title: 'VideoPlatform API'
    description: 'API for VideoPlatform Application.'
    version: '0.0.1'  # The version of the API.
    
    resources:
        refresh_token:
            classes:
                model: App\Entity\Api\RefreshToken


