oneup_flysystem:
    adapters:
        vs_vvp.downloads_adapter:
            local:
                location: '%vs_vvp.videos_directory%'
        vs_vvp.coconut_output_adapter:
            local:
                location: '%vs_vvp.coconut_output_directory%'
                
    filesystems:
        vs_vvp.downloads_filesystem:
            adapter: vs_vvp.downloads_adapter
            alias: League\Flysystem\Filesystem
        vs_vvp.coconut_output_filesystem:
            adapter: vs_vvp.coconut_output_adapter