imports:
    - { resource: video_providers/local_storage.yaml }
    - { resource: video_providers/youtube.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    app_video_transcoder_coconut:
        class: App\Component\Cloud\Coconut
        arguments:
            - '@router'
            - '@doctrine'
            - '@vs_vvp.repository.coconut_job'
            - '@vs_vvp.factory.coconut_job'
            - '@vs_vvp.repository.video_platform_settings'
            - '%vvp_video_platform_settings_slug%'
            
#     app_video_storage_digitalocean:
#         class: App\Component\Cloud\DigitalOcean
#         public: true
#         arguments:
#             - '@router'
#             - '@doctrine'
#             - {
#                 access_token: '%vvp_digitalocean_access_token%'
#             }


