services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Controller\Api\TestController:
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\Api\CoconutWebhookController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@mailer'
            - '@vs_users.notifications'
            - '@vs_vvp.repository.coconut_job'
            - '@vs_api.api_manager'
            #- '@security.token_storage'
            - '@logger'
            
    App\Controller\Api\CoconutStorageController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@request_stack'
            - '@vs_users.notifications'
        

