parameters:
    vs_application.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_application.gaufrette.app_pictures.filesystem: vs_application_app_pictures
    
    vs_vvp.videos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos"
    vs_vvp.video_clips_directory: "%kernel.project_dir%/public/shared_media/gaufrette/video_clips"
    vs_vvp.coconut_output_directory: "%kernel.project_dir%/public/shared_media/gaufrette/coconut_output"
    vs_vvp.actor_photos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/actors"
    vs_vvp.videos_user_signatured_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos_user_signatured"
    vs_vvp.youtube_photos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/youtube_photos"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    # Create a Custom Uploader extending Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
    # Add Needed Configurations in packages/knp_gaufrette.yaml
    ##################################################################################################
#    vs_application.custom_uploader:
#        class: App\Component\Uploader\GamePictureUploader
#        arguments:
#            - '@oneup_flysystem.vs_application_app_pictures_filesystem'
#            - '@vs_cms.file_path_generator'


    vs_vvp.local_video_file_path_generator:
        class: App\Component\VideoUploader\LocalFilePathGenerator
    
    vs_vvp.actor_photo_file_path_generator:
        class: App\Component\ActorPhotoUploader\FilePathGenerator
    
    vs_vvp.video_uploader.local_uploader:
        class: App\Component\VideoUploader\LocalUploader
        arguments:
            - '@oneup_flysystem.vs_vvp_videos_filesystem'
            - '@vs_vvp.local_video_file_path_generator'
            - '@app_video_platform'
            
    vs_vvp.video_photo_uploader:
        class: App\Component\VideoUploader\VideoPhotoUploader
        arguments:
            - '@oneup_flysystem.vs_vvp_videos_filesystem'
            - '@vs_vvp.local_video_file_path_generator'
    
    vs_vvp.video_uploader.video_clip_uploader:
        class: App\Component\VideoUploader\VideoClipUploader
        arguments:
            - '@oneup_flysystem.vs_vvp_video_clips_filesystem'
            - '@vs_vvp.local_video_file_path_generator'
    
    vs_vvp.actor_photo_uploader:
        class: App\Component\ActorPhotoUploader\ActorPhotoUploader
        arguments:
            - '@oneup_flysystem.vs_vvp_actor_photos_filesystem'
            - '@vs_vvp.actor_photo_file_path_generator'
            
    vs_vvp.digital_ocean_original_videos_adapter:
        class: App\Component\VideoUploader\Adapter\LeagueFlysystemAwsS3VideosOriginal
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_original_videos'
            
    vs_vvp.digital_ocean_coconut_output_adapter:
        class: App\Component\VideoUploader\Adapter\LeagueFlysystemAwsS3CoconutOutput
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_coconut_output'
            
    vs_vvp.youtube_photo_uploader:
        class: App\Component\YoutubePhotoUploader
        arguments:
            - '@oneup_flysystem.vs_vvp_youtube_photos_filesystem'
            - '@vs_cms.file_path_generator'
