parameters:
    vs_application.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_application.gaufrette.app_pictures.filesystem: vs_application_app_pictures
    
    vs_vvp.videos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos"
    vs_vvp.coconut_output_directory: "%kernel.project_dir%/public/shared_media/gaufrette/coconut_output"
    vs_vvp.actor_photos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/actors"
    vs_vvp.slider_directory: "%kernel.project_dir%/public/shared_media/gaufrette/slider"
    vs_vvp.videos_user_signatured_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos_user_signatured"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.app_pictures_uploader.filesystem:
        class: Gaufrette\Filesystem
        arguments: ['%vs_application.gaufrette.app_pictures.filesystem%']
        factory: ['@knp_gaufrette.filesystem_map', 'get']
        
    vs_application.app_pictures_uploader:
        class: Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
        arguments:
            - '@vs_application.app_pictures_uploader.filesystem'
            - '@vs_cms.file_path_generator'
    
    # Create a Custom Uploader extending Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
    # Add Needed Configurations in packages/knp_gaufrette.yaml
    ##################################################################################################
#    vs_application.custom_uploader:
#        class: App\Component\Uploader\GamePictureUploader
#        arguments:
#            - '@vs_application.app_pictures_uploader.filesystem'
#            - '@vs_cms.file_path_generator'


    vs_vvp.video_uploader.local_uploader_filesystem:
        class: Gaufrette\Filesystem
        arguments: ['vs_vvp_videos']
        factory: ['@knp_gaufrette.filesystem_map', 'get']
        
    vs_vvp.local_video_file_path_generator:
        class: App\Component\VideoUploader\LocalFilePathGenerator
        
    vs_vvp.video_uploader.local_uploader:
        class: App\Component\VideoUploader\LocalUploader
        arguments:
            - '@vs_vvp.video_uploader.local_uploader_filesystem'
            - '@vs_vvp.local_video_file_path_generator'
            - '@app_video_platform'
            
    vs_vvp.actor_photo_uploader.filesystem:
        class: Gaufrette\Filesystem
        arguments: ['vs_vvp_actor_photos']
        factory: ['@knp_gaufrette.filesystem_map', 'get']
        
    vs_vvp.actor_photo_file_path_generator:
        class: App\Component\ActorPhotoUploader\FilePathGenerator
        
    vs_vvp.actor_photo_uploader:
        class: App\Component\ActorPhotoUploader\ActorPhotoUploader
        arguments:
            - '@vs_vvp.actor_photo_uploader.filesystem'
            - '@vs_vvp.actor_photo_file_path_generator'
            
    vs_vvp.slider_uploader.filesystem:
        class: Gaufrette\Filesystem
        arguments: ['vs_vvp_slider']
        factory: ['@knp_gaufrette.filesystem_map', 'get']
        
    vs_vvp.slider_file_path_generator:
        class: App\Component\SliderPhotoUploader\FilePathGenerator
        
    vs_vvp.slider_uploader:
        class: App\Component\SliderPhotoUploader\SliderPhotoUploader
        arguments:
            - '@vs_vvp.slider_uploader.filesystem'
            - '@vs_vvp.slider_file_path_generator'
    
    vs_vvp.digital_ocean_original_videos_adapter:
        class: App\Component\VideoUploader\Adapter\GaufretteAwsS3VideosOriginal
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_original_videos'
            
    vs_vvp.digital_ocean_coconut_output_adapter:
        class: App\Component\VideoUploader\Adapter\GaufretteAwsS3CoconutOutput
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_coconut_output'


