services:
    _defaults:
        autowire: true
        autoconfigure: true

    app_video_urls_factory:
        class: App\Component\VideoUrlsFactory
        public: true
        arguments:
            - '@router'
            - '@vs_vvp.digital_ocean_original_videos_adapter'
            - '@vs_vvp.digital_ocean_coconut_output_adapter'
            
    app_video_streams_factory:
        class: App\Component\VideoStreamsFactory
        public: true
        arguments:
            - '@vs_vvp.digital_ocean_original_videos_adapter'
            - '@vs_vvp.digital_ocean_coconut_output_adapter'
            - '@oneup_flysystem.vs_vvp.filesystems.local_filesystem'
            - '@oneup_flysystem.vs_vvp.filesystems.coconut_output_filesystem'
            
    app_video_signatory:
        class: App\Component\VideoSignatory
        public: true
        arguments:
            - '@dubture_ffmpeg.ffmpeg'
            - '@security.token_storage'
            - '@oneup_flysystem.vs_vvp.filesystems.videos_user_signatured_filesystem'
            - '%vs_vvp.videos_user_signatured_directory%'
    
    app_video_storage_bridge:
        class: App\Component\VideoStorageBridge
        public: true
        arguments:
            - '@app_video_urls_factory'
            - '@vs_vvp.digital_ocean_original_videos_adapter'
            - '@vs_vvp.digital_ocean_coconut_output_adapter'
            - '%vs_vvp.videos_directory%'
            
    app_video_platform:
        class: App\Component\VideoPlatform
        public: true
        arguments:
            - '@vs_application.context.application'
            - '@app_video_urls_factory'
            - '@app_video_streams_factory'
            - '@app_video_storage_bridge'
            - '@app_video_signatory'

    app_video_transcoder_coconut_video_job:
        class: App\Component\Cloud\Coconut\CoconutVideoJobBuilder
        public: true
        arguments:
            - '@router'
            - '@doctrine'
            - '@vs_vvp.repository.coconut_video_job'
            - '@vs_vvp.factory.coconut_video_job'
            - '@http_client'
            - '@app_video_platform'
            - 'https://api.%vankosoft_host%'
    
    app_video_transcoder_coconut_clip_job:
        class: App\Component\Cloud\Coconut\CoconutClipJobBuilder
        public: true
        arguments:
            - '@router'
            - '@doctrine'
            - '@vs_vvp.repository.coconut_clip_job'
            - '@vs_vvp.factory.coconut_clip_job'
            - '@http_client'
            - '@app_video_platform'
            - 'https://api.%vankosoft_host%'
            
    app_video_resource_listener:
        class: App\EventListener\VideoResourceEventListener
        arguments:
            - '@app_video_transcoder_coconut_video_job'
            - '@app_video_transcoder_coconut_clip_job'
            - '@app_video_platform'
            - '@app_video_clip_maker'
        tags:
           -  { name: kernel.event_listener, event: vs_vvp.video.post_create, method: onVideoCreate }
           
    app_video_storage_digitalocean_original_videos:
        class: App\Component\Cloud\DigitalOceanOriginalVideos
        public: true
        arguments:
            - '@app_video_platform'
            
    app_video_storage_digitalocean_coconut_output:
        class: App\Component\Cloud\DigitalOceanCoconutOutput
        public: true
        arguments:
            - '@app_video_platform'

    app_video_clip_maker:
        class: App\Component\VideoClipMaker
        arguments:
            - '@dubture_ffmpeg.ffmpeg'
            - '@doctrine'
            - '@vs_vvp.factory.video_clip'
            - '%vs_vvp.videos_directory%'
