vs_vvp_video:
    resource: |
        alias: vs_vvp.video
        except: ['show']
        path: /video-platform/video/items
        templates: "admin-panel/pages/Videos"
        form:
            options:
                ckeditor_uiColor: '%vs_users_subscriptions.form.payed_service.ckeditor_uiColor%'
                ckeditor_toolbar: '%vs_users_subscriptions.form.payed_service.ckeditor_toolbar%'
                ckeditor_extraPlugins: '%vs_users_subscriptions.form.payed_service.ckeditor_extraPlugins%'
                ckeditor_removeButtons: '%vs_users_subscriptions.form.payed_service.ckeditor_removeButtons%'
                ckeditor_allowedContent: '%vs_users_subscriptions.form.payed_service.ckeditor_allowedContent%'
                ckeditor_extraAllowedContent: '%vs_users_subscriptions.form.payed_service.ckeditor_extraAllowedContent%'
    type: sylius.resource
    options:
        expose: true

vs_vvp_video_index:
    path: /video-platform/video/items/
    methods: [GET]
    defaults:
        _controller: vs_vvp.controller.video::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            template: "admin-panel/pages/Videos/index.html.twig"
    options:
        expose: true
        
vs_vvp_video_index_filtered:
    path: /video-platform/video/items/{filterCategory}/
    methods: [GET]
    defaults:
        _controller: vs_vvp.controller.video::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            criteria:
                category: $filterCategory
            template: "admin-panel/pages/Videos/index.html.twig"
    options:
        expose: true

vs_vvp_video_category:
    resource: |
        alias: vs_vvp.video_category
        except: ['show']
        path: /video-platform/video/categories
        templates: "admin-panel/pages/VideosCategories"
    type: sylius.resource
    
vs_vvp_helpcenter_question:
    resource: |
        alias: vs_vvp.helpcenter_question
        except: ['show']
        path: /video-platform/helpcenter/questions
        templates: "admin-panel/pages/HelpCenterQuestions"
    type: sylius.resource
    options:
        expose: true

vs_vvp_helpcenter_question_index:
    path: /video-platform/helpcenter/questions/
    methods: [GET]
    defaults:
        _controller: vs_vvp.controller.helpcenter_question::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            template: "admin-panel/pages/HelpCenterQuestions/index.html.twig"
    options:
        expose: true
        
vs_vvp_actor:
    resource: |
        alias: vs_vvp.actor
        except: ['show']
        path: /video-platform/actors
        templates: "admin-panel/pages/Actors"
        form:
            options:
                ckeditor_uiColor: '%vs_users_subscriptions.form.payed_service.ckeditor_uiColor%'
                ckeditor_toolbar: '%vs_users_subscriptions.form.payed_service.ckeditor_toolbar%'
                ckeditor_extraPlugins: '%vs_users_subscriptions.form.payed_service.ckeditor_extraPlugins%'
                ckeditor_removeButtons: '%vs_users_subscriptions.form.payed_service.ckeditor_removeButtons%'
                ckeditor_allowedContent: '%vs_users_subscriptions.form.payed_service.ckeditor_allowedContent%'
                ckeditor_extraAllowedContent: '%vs_users_subscriptions.form.payed_service.ckeditor_extraAllowedContent%'
    type: sylius.resource
    options:
        expose: true

vs_vvp_actor_index:
    path: /video-platform/actors/
    methods: [GET]
    defaults:
        _controller: vs_vvp.controller.actor::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            template: "admin-panel/pages/Actors/index.html.twig"
    options:
        expose: true
        
vs_vvp_quick_link:
    resource: |
        alias: vs_vvp.quick_link
        except: ['show']
        path: /video-platform/quick-links
        templates: "admin-panel/pages/QuickLinks"
    type: sylius.resource
    options:
        expose: true

vs_vvp_quick_link_index:
    path: /video-platform/quick-links/
    methods: [GET]
    defaults:
        _controller: vs_vvp.controller.quick_link::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            template: "admin-panel/pages/QuickLinks/index.html.twig"
    options:
        expose: true

vs_vvp_slider:
    resource: |
        alias: vs_vvp.slider
        except: ['show']
        path: /video-platform/sliders
        templates: "admin-panel/pages/Sliders"
        form:
            options:
                ckeditor_uiColor: '%vs_users_subscriptions.form.payed_service.ckeditor_uiColor%'
                ckeditor_toolbar: '%vs_users_subscriptions.form.payed_service.ckeditor_toolbar%'
                ckeditor_extraPlugins: '%vs_users_subscriptions.form.payed_service.ckeditor_extraPlugins%'
                ckeditor_removeButtons: '%vs_users_subscriptions.form.payed_service.ckeditor_removeButtons%'
                ckeditor_allowedContent: '%vs_users_subscriptions.form.payed_service.ckeditor_allowedContent%'
                ckeditor_extraAllowedContent: '%vs_users_subscriptions.form.payed_service.ckeditor_extraAllowedContent%'
    type: sylius.resource
    options:
        expose: true

vs_vvp_slider_index:
    path: /video-platform/sliders/
    methods: [GET]
    defaults:
        _controller: vs_vvp.controller.slider::indexAction
        _sylius:
            paginate: 10
            sortable: true
            sorting:
                updatedAt: desc
            filterable: true
            template: "admin-panel/pages/Sliders/index.html.twig"
    options:
        expose: true
        
vs_vvp_coconut_settings:
    resource: |
        alias: vs_vvp.coconut_settings
        except: ['show']
        path: /video-platform/coconut-settings
        templates: "admin-panel/pages/CoconutSettings"
    type: sylius.resource
    options:
        expose: true

vs_vvp_settings:
    resource: |
        alias: vs_vvp.video_platform_settings
        except: ['show']
        path: /video-platform/video-platform-settings
        templates: "admin-panel/pages/VideoPlatformSettings"
    type: sylius.resource
    options:
        expose: true
        
vs_vvp_storage:
    resource: |
        alias: vs_vvp.video_platform_storage
        except: ['show']
        path: /video-platform/video-platform-storage
        templates: "admin-panel/pages/VideoPlatformStorage"
    type: sylius.resource
    options:
        expose: true
        
vs_vvp_google_cloud_project:
    resource: |
        alias: vs_vvp.google_cloud_project
        except: ['show']
        path: /video-platform/google-cloud-projects
        templates: "admin-panel/pages/GoogleCloudProject"
    type: sylius.resource
    options:
        expose: true
        
vs_vvp_youtube_channel:
    resource: |
        alias: vs_vvp.youtube_channel
        except: ['show']
        path: /video-platform/youtube-channels
        templates: "admin-panel/pages/YoutubeChannel"
    type: sylius.resource
    options:
        expose: true


