imports:
    - { resource: services/security.yaml }
    - { resource: services/controller.yaml }
    - { resource: services/form.yaml }
    - { resource: services/doctrine_extensions.yaml }
    - { resource: services/menu.yaml }
    - { resource: services/youtube.yaml }
    - { resource: services/video-player.yaml }
    - { resource: services/uploader.yaml }
    - { resource: services/twig.yaml }
    - { resource: services/widgets.yaml }
    
parameters:
    locale: 'en_US'

    vankosoft_host: '%env(HOST)%'
    applicationTitle: 'VS Video Platform'
    
    vs_application.version: !php/const App\VideoPlatformKernel::VERSION
    vs_application.public_dir: "%kernel.project_dir%/public/video-platform"
    
    vs_users.login_route: 'app_login'
    vs_users.login_by: 'username'
    vs_users.default_redirect: 'app_home'
    vs_users.form_create_account: false
    
    # The cookie_lifetime would be set to a relatively high value, 
    # and the garbage collection gc_maxlifetime would be set to destroy sessions at whatever the desired idle period is.
    #########################################################################################################################
    vs_users.gc_maxlifetime: 1800   # 30 minutes
    vs_users.cookie.domain: '%env(COOKIE_DOMAIN)%'
    vs_users.cookie.lifetime: 86400 # 24 hours
    
    # Gaufrette File Systems
    vs_cms.gaufrette.profile.filesystem: vs_application_profile
    vs_cms.gaufrette.filemanager.filesystem: vs_application_filemanager
    vs_cms.gaufrette.slider.filesystem: vs_application_slider
    
    # Shared Media Directories
    vs_cms.filemanager_shared_media_gaufrette.profile: "%kernel.project_dir%/public/shared_media/gaufrette/profile"
    vs_cms.filemanager_shared_media_gaufrette.filemanager: "%kernel.project_dir%/public/shared_media/gaufrette/filemanager"
    vs_cms.filemanager_shared_media_artgris: '%kernel.project_dir%/public/shared_media/artgris'
    vs_cms.filemanager_shared_media_gaufrette.slider: "%kernel.project_dir%/public/shared_media/gaufrette/slider"
    
    vs_application.taxon_repository_throw_exception: false
    vs_application.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    
    vs_payment.shopping_cart_redirect_on_payment_done: 'app_home'
    vs_payment.pricing_plans_redirect_on_payment_done: 'vs_payment_pricing_plans'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/DataFixtures/'
            - '../../../src/DependencyInjection/'
            - '../../../src/Entity/'
            - '../../../src/Form/'
            - '../../../src/Tests/'
            - '../../../src/Controller/'
            - '../../../src/Widgets/'
            - '../../../src/Component/'
            - '../../../src/Command/'
            - '../../../src/VideoPlatformKernel.php'
        autowire: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    