app_vs_payment_payment:
    resource: "@VSPaymentBundle/Resources/config/routing/payment.yaml"
    prefix: /

app_vs_payment_checkout:
    resource: "@VSPaymentBundle/Resources/config/routing/checkout.yaml"
    prefix: /

app_vs_payment_products:
    resource: "@VSPaymentBundle/Resources/config/routing/products.yaml"
    prefix: /

vs_payment_pricing_plans:
    path: /pricing-plans-checkout
    controller: App\Controller\VideoPlatform\PricingPlanCheckoutController::showPricingPlans
    options:
        expose: true
