services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Controller\Api\GetPicingPlanCouponController:
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_catalog.repository.pricing_plan'
            
    App\Controller\Api\CheckValidPricingPlanCouponController:
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_catalog.repository.pricing_plan'

    App\Controller\Api\CoconutWebhookController:
        tags: ['controller.service_arguments']
        arguments:
            - '@logger'
            - '@doctrine'
            - '@mailer'
            - '@vs_users.notifications'
            - '@vs_vvp.repository.coconut_video_job'
            - '@vs_vvp.repository.coconut_clip_job'
            - '@vs_vvp.factory.video_clip'
            - '@vs_api.api_manager'
            - '@app_video_clip_maker'
    
    App\Controller\Api\CoconutNormalUploaderController:
        tags: ['controller.service_arguments']
        arguments:
            - '@logger'
            - '@doctrine'
            - '@mailer'
            - '@vs_vvp.repository.video'
            #- '@vs_vvp.video_uploader.video_clip_uploader'
            - '@oneup_flysystem.vs_vvp_video_clips_filesystem'
            - '@vs_users.notifications'
