parameters:
    vs_application.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_application.gaufrette.app_pictures.filesystem: vs_application_app_pictures
    
    vs_vvp.videos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos"
    vs_vvp.video_clips_directory: "%kernel.project_dir%/public/shared_media/gaufrette/video_clips"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Create a Custom Uploader extending Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
    # Add Needed Configurations in packages/knp_gaufrette.yaml
    ##################################################################################################
#    vs_application.custom_uploader:
#        class: App\Component\Uploader\GamePictureUploader
#        arguments:
#            - '@vs_application.app_pictures_uploader.filesystem'
#            - '@vs_cms.file_path_generator'

    vs_vvp.local_video_file_path_generator:
        class: App\Component\VideoUploader\LocalFilePathGenerator
    
    vs_vvp.video_uploader.video_clip_uploader:
        class: Vankosoft\CmsBundle\Component\Uploader\FileUploader
        arguments:
            - '@oneup_flysystem.vs_vvp_video_clips_filesystem'
            - '@vs_vvp.local_video_file_path_generator'
