parameters:
    
    vs_vvp.videos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Create a Custom Uploader extending Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
    # Add Needed Configurations in packages/knp_gaufrette.yaml
    ##################################################################################################
#    vs_application.custom_uploader:
#        class: App\Component\Uploader\GamePictureUploader
#        arguments:
#            - '@vs_application.app_pictures_uploader.filesystem'
#            - '@vs_cms.file_path_generator'
