parameters:
    vs_application.menu.config_file: "%kernel.project_dir%/config/applications/video-platform/packages/vs_application.yaml"
    vs_application.main_menus: ['mainVideoPlatformMenu', 'mainFooterMenu', 'profileMenu']

services:
    # Custom Menus
    ######################################################
    video_platform.main_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory", 'mainVideoPlatformMenu']
        tags:
            - { name: knp_menu.menu, alias: mainVideoPlatform }
            
    video_platform.footer_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory", 'mainFooterMenu']
        tags:
            - { name: knp_menu.menu, alias: mainFooter }
