parameters:
    vs_application.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_application.gaufrette.app_pictures.filesystem: vs_application_app_pictures

    vs_vvp.slider_directory: "%kernel.project_dir%/public/shared_media/gaufrette/slider"
    vs_vvp.videos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos"
    vs_vvp.coconut_output_directory: "%kernel.project_dir%/public/shared_media/gaufrette/coconut_output"
    vs_vvp.videos_user_signatured_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos_user_signatured"
    
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.app_pictures_uploader.filesystem:
        class: Gaufrette\Filesystem
        arguments: ['%vs_application.gaufrette.app_pictures.filesystem%']
        factory: ['@knp_gaufrette.filesystem_map', 'get']
        
    vs_application.app_pictures_uploader:
        class: Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
        arguments:
            - '@vs_application.app_pictures_uploader.filesystem'
            - '@vs_cms.file_path_generator'
    
    vs_vvp.digital_ocean_original_videos_adapter:
        class: App\Component\VideoUploader\Adapter\GaufretteAwsS3VideosOriginal
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_original_videos'
            
    vs_vvp.digital_ocean_coconut_output_adapter:
        class: App\Component\VideoUploader\Adapter\GaufretteAwsS3CoconutOutput
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_coconut_output'


