parameters:

    vs_vvp.slider_directory: "%kernel.project_dir%/public/shared_media/gaufrette/slider"
    vs_vvp.videos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos"
    vs_vvp.video_clips_directory: "%kernel.project_dir%/public/shared_media/gaufrette/video_clips"
    vs_vvp.coconut_output_directory: "%kernel.project_dir%/public/shared_media/gaufrette/coconut_output"
    vs_vvp.actor_photos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/actors"
    vs_vvp.videos_user_signatured_directory: "%kernel.project_dir%/public/shared_media/gaufrette/videos_user_signatured"
    vs_vvp.youtube_photos_directory: "%kernel.project_dir%/public/shared_media/gaufrette/youtube_photos"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    vs_vvp.digital_ocean_original_videos_adapter:
        class: App\Component\VideoUploader\Adapter\LeagueFlysystemAwsS3Adapter
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_original_videos'
            
    vs_vvp.digital_ocean_coconut_output_adapter:
        class: App\Component\VideoUploader\Adapter\LeagueFlysystemAwsS3Adapter
        lazy: true
        arguments:
            - '@app_video_storage_digitalocean_coconut_output'
