services:
    _defaults:
        autowire: true
        autoconfigure: true

    app_google_client:
        class: App\Component\Cloud\Google
        arguments:
            - '@vs_vvp.repository.google_cloud_project'
    
    app_video_provider_youtube:
        class: App\Component\Cloud\GoogleVideoProvider
        arguments:
            - '@app_google_client'

    app_video_service_youtube:
        class: App\Component\VideoPlayer\VideoService
        arguments:
            - '@app_video_provider_youtube'


